### PR TITLE
Implement a release workflow

### PR DESCRIPTION
**Pull request by Haarolean**
Example run: [here](https://github.com/Haarolean/kafka-connect-reddit/actions/runs/4681307916/jobs/8293729966)
A release with the uploaded jar: [here](https://github.com/Haarolean/kafka-connect-reddit/releases/tag/1.0.1)
Also, the jar is downloadable on the action run' page: [here](https://github.com/Haarolean/kafka-connect-reddit/actions/runs/4681307916)

### CODE REVIEW

**Comment by C0urante** [comment]
It looks like the artifact contains the jar for the connector, but not any of its dependencies (like JRAW, for example). I believe the dependencies are required for the connector to work.

Have you tried running the connector locally on a Kafka Connect worker with the artifacts generated by the build?

**Comment by C0urante** [comment]
Oh, and most importantly--thank you for taking this on! I really appreciate it.

**Comment by Haarolean** [comment]
Welp, the readme contained just the clean package command, so I believed it was enough. I’ll look into shading w/ maven tomorrow.

**Comment by C0urante** [comment]
I think what we want to provide is the file in the `target/components/pacakges` directory mentioned in the [local build](https://github.com/C0urante/kafka-connect-reddit/#local-build) section? That should have everything we need, no need to add shading logic to the build file.

**Comment by Haarolean** [comment]
@C0urante done I suppose

**Comment by Haarolean** [comment]
@C0urante bump?:)

**Review by C0urante — APPROVED** [review]
Sorry for the delay @Haarolean. Thanks, LGTM!

Tested locally with the [C0urante-kafka-connect-reddit-0.2.0-SNAPSHOT.zip](https://github.com/Haarolean/kafka-connect-reddit/releases/download/1.0.2/C0urante-kafka-connect-reddit-0.2.0-SNAPSHOT.zip) artifact generated in the [test4](https://github.com/Haarolean/kafka-connect-reddit/releases/tag/1.0.2) release on your fork. Everything ran smoothly; the connector was able to start and read content from Reddit successfully.

**Comment by Haarolean** [comment]
@C0urante thanks much! Can we run a release now?:)

**Pull request merged**
